backend:
  name: git-gateway
media_folder: static/assets
public_folder: /assets
collections:
  - name: team
    label: Team
    label_singular: Team member
    folder: _collections/team
    create: true
    fields:
      - { name: avatar, label: Avatar, widget: image}
      - { name: title, label: Full name }
      - { name: role, label: Role }
      - { name: linkedin, label: Linkedin }
      - { name: bio, label: Bio, widget: text }
  - name: services
    label: Services
    label_singular: Service
    folder: _collections/services
    create: true
    fields:
      - { name: icon, label: Icon, widget: image}
      - { name: title, label: Service name }
      - { name: description, label: Description, widget: text }
